### ISSUE TITLE
sbt -> test does not run all tests

### ISSUE THREAD

**Issue by ghost** [lagom/activator-lagom-java-chirper#8] opened 2016-03-17 13:28 UTC
Maybe its by design...

'test' from sbt console runs only ChirpServiceTest and ActivityStreamServiceTest

> test
> [info] Compiling 1 Java source to /Users/michalkarolik/workspace/lagom/activator-lagom-java-chirper/friend-impl/target/scala-2.11/test-classes...
> [info] Test run started
> [info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetLiveFeed started
> [info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetHistoricalFeed started
> [info] Test run finished: 0 failed, 0 ignored, 2 total, 4.413s
> [info] Passed: Total 2, Failed 0, Errors 0, Passed 2
> [info] Test run started
> 2016-03-17 14:23:08,782 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
> [warn] a.s.Serialization(akka://ServiceTest_160317142307630) - Using the default Java serializer for class [java.lang.String] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
> [info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldPublishShirpsToSubscribers started
> [info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldRetrieveOldChirps started
> [info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldIncludeSomeOldChirpsInLiveFeed started
> [info] Test run finished: 0 failed, 0 ignored, 3 total, 20.313s
> [info] Passed: Total 3, Failed 0, Errors 0, Passed 3
> [success] Total time: 29 s, completed Mar 17, 2016 2:23:30 PM

**Comment by dotta** [comment] 2016-03-18 16:53
Definitely not by design, thanks for reporting it.

**Comment by dotta** [comment] 2016-03-18 17:07
Mmm, something is not right. I added the following project in the build.sbt, which manually does the aggregation on the root project, and then running `test` does execute all tests.

```
lazy val root = (sbt.project in file("."))
  .aggregate(friendApi, friendImpl, chirpApi, chirpImpl, activityStreamApi, activityStreamImpl, loadTestApi, loadTestImpl)
```

Right, so, I removed the above project from the build file, hit `reload`, and then `test`. Well, now it seems to work fine !?!?! (and that, even after restarting the sbt console)

@michalkarolik Could you try to repeat the same steps and see if you get the same result?

**Comment by ghost** [comment] 2016-03-18 18:42
Im SBT newbie, but for me adding this line gave no result ( still onlyActivityStreamServiceTest and ChirpServiceTest are run ). Ive tried with 'reload' and then 'test' and also running sbt console again. No effect.

I had to put 'clean' and then FriendServiceTest FriendEntityTest started to run on 'test' command.

Then, I removed your `lazy val root...` line... but all tests were running, no matter how many 'reload'/'clean' running sbt console again Ive tried. : )

Then I cloned project to /tmp path, run sbt, and test - all tests are running fine.

By 'all' I mean:
`info] Test run started
2016-03-18 19:39:17,863 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[warn] a.s.Serialization(akka://ServiceTest_160318193915656) - Using the default Java serializer for class [java.lang.String] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldPublishShirpsToSubscribers started
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldRetrieveOldChirps started
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldIncludeSomeOldChirpsInLiveFeed started
[info] Test run finished: 0 failed, 0 ignored, 3 total, 20.483s
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[info] Test run started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testAddDuplicateFriend started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testCreateUserWithInitialFriends started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testGetUser started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testRejectDuplicateCreate started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testAddFriend started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testCreateUser started
[info] Test run finished: 0 failed, 0 ignored, 6 total, 1.287s
[info] Test run started
[info] Test sample.chirper.friend.impl.FriendServiceTest.shouldBeAbleToCreateUsersAndConnectFriends started
2016-03-18 19:39:41,089 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[warn] a.s.Serialization(akka://ServiceTest_160318193940249) - Using the default Java serializer for class [java.lang.String] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[info] Test run finished: 0 failed, 0 ignored, 1 total, 24.753s
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
[info] Test run started
[info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetLiveFeed started
[info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetHistoricalFeed started
[info] Test run finished: 0 failed, 0 ignored, 2 total, 3.863s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 84 s, completed Mar 18, 2016 7:40:12 PM

> `

**Comment by dotta** [comment] 2016-03-21 09:09
@michalkarolik Thanks for trying it out. There it seems to be something fishy with sbt state. @jroper Any idea?

**Comment by TimMoore** [comment] 2016-11-16 03:46
Hi @michalkarolik I'm just following up on this issue.

I'm seeing all of the tests run when I try it with the latest master:

```
$ sbt
[info] Loading project definition from /Users/tmoore/Projects/lagom/activator-lagom-java-chirper/project
[info] Set current project to activator-lagom-java-chirper (in build file:/Users/tmoore/Projects/lagom/activator-lagom-java-chirper/)
> test
[info] Compiling 2 Scala sources to /Users/tmoore/Projects/lagom/activator-lagom-java-chirper/front-end/target/scala-2.11/classes...
[info] Test run started
2016-11-16 14:44:36,964 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldPublishShirpsToSubscribers started
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldRetrieveOldChirps started
[info] Test sample.chirper.chirp.impl.ChirpServiceTest.shouldIncludeSomeOldChirpsInLiveFeed started
[info] Test run finished: 0 failed, 0 ignored, 3 total, 16.67s
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[info] Test run started
[info] Test sample.chirper.friend.impl.FriendServiceTest.shouldBeAbleToCreateUsersAndConnectFriends started
2016-11-16 14:44:56,004 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[error] a.a.OneForOneStrategy - Processor actor [Actor[akka://ServiceTest_161116144455325/user/StreamSupervisor-0/flow-3-3-mapAsync#-1261087515]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_161116144455325/user/StreamSupervisor-0/flow-3-3-mapAsync#-1261087515]] terminated abruptly
[info] Test run finished: 0 failed, 0 ignored, 1 total, 18.366s
[info] Test run started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testAddDuplicateFriend started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testCreateUserWithInitialFriends started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testGetUser started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testRejectDuplicateCreate started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testAddFriend started
[info] Test sample.chirper.friend.impl.FriendEntityTest.testCreateUser started
[info] Test run finished: 0 failed, 0 ignored, 6 total, 0.956s
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
[info] Test run started
[info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetLiveFeed started
[info] Test sample.chirper.activity.impl.ActivityStreamServiceTest.shouldGetHistoricalFeed started
[info] Test run finished: 0 failed, 0 ignored, 2 total, 3.243s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 47 s, completed 16/11/2016 2:45:21 PM
```

Can you try again and see if it's still happening to you? Thanks!

**Comment by ignasi35** [comment] 2016-11-16 19:09
In a fresh clone of the repo I observed the symptoms described. I can't reproduce it now (tried cloning again few times).
The symptoms I observed were: sbt test runs some but not all tests. In my case in particular, `ChirpServiceTest.*` were not run. Adding a new line (or maybe `touch`?) to all non-run tests made them available on sbt.

**Comment by TimMoore** [comment] 2018-02-26 05:19
Closing this, since we don't know how to reproduce it and it has been idle for some time.

**Closed as completed by TimMoore** 2018-02-26 05:19 UTC
Labels: bug
