### ISSUE TITLE
Adding chirp (message) did not work out of box

### ISSUE THREAD

**Issue by kaiyuan01** [lagom/activator-lagom-java-chirper#107] opened 2018-01-28 19:23 UTC
I started the project with runAll just as instructed in Linux. All looks fine. However, when I try to add a post (chirp) after logging into the page and hitting "Post" button, nothing happens. Feed also shows nothing. No errors from server logs as well. How can I troubleshoot this? The error from the log:

> 20:36:30.592 [info] akka.actor.RepointableActorRef [sourceThread=chirp-impl-application-akka.actor.default-dispatcher-4, akkaTimestamp=01:36:30.592UTC, akkaSource=akka://chirp-impl-application/system/distribu
> tedPubSubMediator, sourceActorSystem=chirp-impl-application] - Message [sample.chirper.chirp.api.Chirp] from Actor[akka://chirp-impl-application/deadLetters] to Actor[akka://chirp-impl-application/system/dist
> ributedPubSubMediator#-545811876] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-dur
> ing-shutdown'.

**Comment by octonato** [comment] 2018-01-29 11:20
@kaiyuan01 check your logs to see if there are other errors, like something failing to startup. 

I will invite you to join our Gitter channel at https://gitter.im/lagom/lagom?utm_source=share-link&utm_medium=link&utm_campaign=share-link. That's a more suitable place for this kind of troubleshooting question. We keep GitHub for bug reports and change requests. 

PS: I'm closing this issue because that's not a bug report. The application is working as expected.

**Closed as completed by octonato** 2018-01-29 11:20 UTC
Labels: invalid
